### ISSUE TITLE
[Bug]: 卡片节点每次输入或退格，高度都会自动增加。

### ISSUE THREAD

**Issue by Wooden-Gear** [Quorafind/Obsidian-Node-Auto-Resize#1]
### Bug Description

卡片节点每次输入或退格，高度都会自动增加。

### Relevant Screenshot

![PixPin_2024-08-06_06-47-19](https://github.com/user-attachments/assets/47c8c8a6-7948-4f15-91fb-c2e05b08a0a8)

### To Reproduce

很久没用canvas了，今天打开使用就一直这样。

### Obsidian Version

V1.6.7

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
有使用任何主题或者主题片段吗？

**Comment by Wooden-Gear** [comment]
> 有使用任何主题或者主题片段吗？

用的Blue  Topaz 主题，除了更改了主题的header 颜色，其他都是用的默认主题设置。

**Comment by Wooden-Gear** [comment]
查出来了，跟Typewriter  Scroll 这个插件冲突了。把这个插件关掉就好了。
@Quorafind
