### ISSUE TITLE
[Bug]: Scaling does not adjust properly for bigger text

### ISSUE THREAD

**Issue by YolloPlays** [Quorafind/Obsidian-Node-Auto-Resize#2]
### Bug Description

If you make a header inside your scaling box i can see it trying to auto adjust the WIDTH of the box according to the text width that the text would have had originally, eventho the text is actually wider, because it is a header for example.

In the provided screenshot you can see `+++Text` ist scaled to the same width as `## Text` when it should be sized diffrently when working with headers.

### Relevant Screenshot

![grafik](https://github.com/user-attachments/assets/b62baa58-09e3-4237-84b5-9d84da84406b)

### To Reproduce

1. Make a Node
2. Try to type in a header (###)
3. See that it is scaling according to character count not the actual displayed size

### Obsidian Version

1.6.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
DONE. Tks for contributing!
